repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace  # убирает лишние пробелы
    -   id: check-yaml  # проверяет синтаксис .yaml файлов
    -   id: check-json  # проверяет синтаксис .json файлов
        exclude: launch.json
    -   id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
    -   id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.
#    -   id: double-quote-string-fixer  # заменяет " на '
    -   id: end-of-file-fixer  # добавляет пустую строку в конце файла

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: "migrations"
        args: ["--ignore=F821,F403,F405,C901", "--max-line-length=129"]

# Отсортировывает импорты в проекте
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)



## Обновляет синтаксис Python кода в соответствии с последними версиями
#-   repo: https://github.com/asottile/pyupgrade
#    rev: v2.31.1
#    hooks:
#    -   id: pyupgrade
#        args: [--py310-plus, --keep-runtime-typing]

## Форматирует код под PEP8
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v2.0.4
#    hooks:
#    -   id: autopep8
#        args: [--max-line-length=100, --in-place]
